export const mockData = {
  order: [
    {
      id: 1,
      content: "Total Orders",
      count: "75",
      percent: 3,
    },
    {
      id: 2,
      content: "Total Delivered",
      count: "70",
      percent: -3,
    },
    {
      id: 3,
      content: "Total Cancelled",
      count: "05",
      percent: 3,
    },
    {
      id: 4,
      content: "Total Revenue",
      count: "$12K",
      percent: -3,
    },
  ],
  netprofit: {
    amount: "$ 6759.25",
    percent: 70,
    profit: 3,
  },
  activity: [
    { name: "9", pv: 2400 },
    { name: "10", pv: 1398 },
    { name: "11", pv: 9800 },
    { name: "12", pv: 3908 },
    { name: "13", pv: 4800 },
    { name: "14", pv: 3800 },
    { name: "15", pv: 4300 },
    { name: "16", pv: 9800 },
    { name: "17", pv: 3908 },
    { name: "18", pv: 4800 },
    { name: "19", pv: 3800 },
    { name: "20", pv: 4300 },
    { name: "21", pv: 4300 },
  ],
  recentorders: [
    {
      id: 1,
      name: "Wade Warden",
      orderno: "23456",
      amount: "2890.9",
      status: "delivered",
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors9.png",
    },
    {
      id: 2,
      name: "Jane coper",
      orderno: "456234",
      amount: "9090.9",
      status: "delivered",
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors5.png",
    },
    {
      id: 3,
      name: "James Howking",
      orderno: "23456",
      amount: "2890.9",
      status: "cancelled",
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors8.png",
    },
    {
      id: 4,
      name: "Kristan Warden",
      orderno: "56123",
      amount: "1190.9",
      status: "cancelled",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQrP5SKPEahxeCKe57TAjT9DXHQoZYJ_J611CmLCkAU2aeEs3pzHdoClLt3TvCMey1kuY&usqp=CAU",
    },
    {
      id: 5,
      name: "Code Fisher",
      orderno: "46756",
      amount: "2890.9",
      status: "delivered",
      img: "https://media1.popsugar-assets.com/files/thumbor/FAA45nfGItBeolNPoqe_Zg89Sls/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2014/01/03/970/n/1922398/bd8f1f25ed3a9f29_114449086_10/i/Bradley-blue-eyes-were-display-Hollywood-premiere.jpg",
    },
    {
      id: 6,
      name: "Ronaldo",
      orderno: "987456",
      amount: "2890.9",
      status: "delivered",
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors10.png",
    },
  ],
  feedback: [
    {
      id: 1,
      name: "Wade Warden",
      star: 5,
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors9.png",
      comment:
        "Had dinner here recently. My husband ordered the Italian calzone. It came out as a 10” size dinner portion. He claimed it was delicious. The service was excellent.",
    },
    {
      id: 2,
      name: "Jane coper",
      star: 4,
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors5.png",
      comment:
        "We always get pizza here at least once during our summer visit. Breakfasts are hardy. All menu options are tasty- truffle fries- the best!!!",
    },
    {
      id: 3,
      name: "James Howking",
      star: 4,
      img: "https://static.javatpoint.com/top10-technologies/images/top-10-hollywood-actors8.png",
      comment:
        "This place knows how to satisfy their clients. Always with a super nice mindset. The food is affordably priced, always delicious and clean.",
    },
  ],
};
